/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.integracion.factory;

import edu.co.sena.tiendaenlinea.integracion.jdbc.CuentaDaoImpl;
import edu.co.sena.tiendaenlinea.integracion.dao.CuentaDao;
import java.sql.Connection;

public class CuentaDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return CuentaDao
	 */
	public static CuentaDao create()
	{
		return new CuentaDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return CuentaDao
	 */
	public static CuentaDao create(Connection conn)
	{
		return new CuentaDaoImpl( conn );
	}

}
