/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.integracion.factory;

import edu.co.sena.tiendaenlinea.integracion.jdbc.ItemCarritoDaoImpl;
import edu.co.sena.tiendaenlinea.integracion.dao.ItemCarritoDao;
import java.sql.Connection;

public class ItemCarritoDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return ItemCarritoDao
	 */
	public static ItemCarritoDao create()
	{
		return new ItemCarritoDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return ItemCarritoDao
	 */
	public static ItemCarritoDao create(Connection conn)
	{
		return new ItemCarritoDaoImpl( conn );
	}

}
