/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.integracion.factory;

import edu.co.sena.tiendaenlinea.integracion.jdbc.PedidoDaoImpl;
import edu.co.sena.tiendaenlinea.integracion.dao.PedidoDao;
import java.sql.Connection;

public class PedidoDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return PedidoDao
	 */
	public static PedidoDao create()
	{
		return new PedidoDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return PedidoDao
	 */
	public static PedidoDao create(Connection conn)
	{
		return new PedidoDaoImpl( conn );
	}

}
