/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.factory;

import java.sql.Connection;
import edu.co.sena.tiendaenlinea.dao.*;
import edu.co.sena.tiendaenlinea.jdbc.*;

public class CatalogoDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return CatalogoDao
	 */
	public static CatalogoDao create()
	{
		return new CatalogoDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return CatalogoDao
	 */
	public static CatalogoDao create(Connection conn)
	{
		return new CatalogoDaoImpl( conn );
	}

}
